### ISSUE TITLE
Make a new proper sidebar on the Homepage

### ISSUE THREAD

**Issue by rakaar** [AdarshKumar712/MathsDep_Website#10]
Currently, the sidebar present on the page just contains the links and is too simple. Make it better, show your design skills. You can look at [this](https://www.designcouncil.org.uk/news-opinion/search) for reference. Also explore your own design ideas.
*This is the sidebar that needs to be changed*
![Screenshot from 2019-12-08 22-40-12](https://user-images.githubusercontent.com/44907757/70393036-ff651b00-1a0b-11ea-8c8f-112d9cb31072.png)

**Comment by leonardomaier** [comment]
@AdarshKumar712 @rakaar please, assign me on this issue. Thanks!

**Comment by thanksalot123** [comment]
sir can i work on this too

**Comment by leonardomaier** [comment]
#13
