### ISSUE TITLE
Design improvements in header

### ISSUE THREAD

**Issue by RajatBachhawat** [AdarshKumar712/MathsDep_Website#14]
The text inside the header needs to be more catchy and better emphasized upon. Also, the IITKGP logo needs to replaced by a png with no white background and inverted colors, so that it looks better and cleaner.

**Comment by AdarshKumar712** [comment]
@RajatBachhawat make the changes as you may think appropriate. Do save the png in the same folder as the logo is in right now. Go ahead!

**Comment by RajatBachhawat** [comment]
Yes sure.
