### ISSUE TITLE
Design changes in Professor Information

### ISSUE THREAD

**Issue by rakaar** [AdarshKumar712/MathsDep_Website#5]
The professor's information is currently well functioning. But there is a scope of good design improvements in this section. Some of them, which I think can be implemented is keeping things in the center, changing suitable font size and font style if you wish. And you can design it as you like. But please ensure that you don't break the functionality :sweat_smile: 
P.S Do add a screen shot of the design change in the PR

**Comment by Nishantgoyal918** [comment]
I want to work on this issue

**Comment by rakaar** [comment]
@Nishantgoyal918  Go ahead.

**Comment by AdarshKumar712** [comment]
@Nishantgoyal918 what is the current status for this issue?

**Comment by rakaar** [comment]
#19 fixes it
