### ISSUE TITLE
Events and News holders in the home page

### ISSUE THREAD

**Issue by rakaar** [AdarshKumar712/MathsDep_Website#6]
The Events and news on the home page need to store a list of information. Design them accordingly, currently, a very preliminary version is setup. If you have any other design ideas, feel free to mention them and work on them.

**Comment by gowripratyusha28** [comment]
I would like to work on this. Can you please tell me what all needs to be stored for an event ?

**Comment by rakaar** [comment]
@gowripratyusha28 The events should contain a list of events info - heading and description. In a each event list element you can keep a heading sought of thing with description beside.
For news, just a list of text elements. 
For testing purposes, you can keep some random text for now at both the places. Later, we shall integrate it with the backend.
