### ISSUE TITLE
Footer design improvments

### ISSUE THREAD

**Issue by rakaar** [AdarshKumar712/MathsDep_Website#7]
The footer contains some social media links, in the form of icons, which are not fitting. Also, there is some odd white space below the footer, which needs to be removed. If you have any other design changes implement them and put a screenshot of it in the PR message.

**Comment by vinitraj412** [comment]
@rakaar can i work on this?

**Comment by rakaar** [comment]
@vinitraj412  Go ahead

**Comment by rakaar** [comment]
#18 fixes it
