### ISSUE TITLE
Contact form design improvements

### ISSUE THREAD

**Issue by rakaar** [AdarshKumar712/MathsDep_Website#8]
The current contact form is a very simple one. You can get design inspiration from other websites and change it accordingly.  Your new ideas are always welcome

**Comment by 1880akshay** [comment]
I want to work on this issue.

**Comment by rakaar** [comment]
@1880akshay  You can go ahead. Take your own time to explore things, learn more about design, experiment with stuff. The coding period starts from 7th December.

**Comment by 1880akshay** [comment]
@rakaar I had a doubt like if I submit a PR before 7th December, will it be counted in my kwoc progress?

**Comment by rakaar** [comment]
@1880akshay Not sure about it. You can do something like this. Code and Submit a PR and I will merge it only after 7th. Hope this is fine.

**Comment by 1880akshay** [comment]
Yeah that is perfectly fine. Thanks

**Comment by promaroy** [comment]
Can I work on this issue?

**Comment by rakaar** [comment]
@promaroy, there is already someone else working on this issue. For now what you can do is, check out the website, if you feel like there is a scope of design improvement at any place, you open an issue and start working on it.

**Comment by AdarshKumar712** [comment]
@1880akshay What is your development status on this issue?

**Comment by 1880akshay** [comment]
@AdarshKumar712 I am about to make a PR for the issue in a day or two.

**Comment by AdarshKumar712** [comment]
Ok, Great!

**Comment by 1880akshay** [comment]
Can you please check the PR I made to improve the design of the Contact us form and tell the necessary changes?

**Comment by AdarshKumar712** [comment]
Great work @1880akshay
