### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by sgpritam** [AdarshKumar712/MathsDep_Website#9]
Update readme for beginner level contibutor

**Comment by sgpritam** [comment]
@AdarshKumar712 Please review

**Comment by rakaar** [comment]
@sgpritam There is a file called `CONTRIBUTION_KWOC.md` , there it contains some beginner instructions. You can have a look at that once

**Comment by AdarshKumar712** [comment]
I have mentioned the same in the readme.md
